export const namesMatrix: string[][] = [
  [
    "Alice",
    "Bob",
    "Carol",
    "Dave",
    "Eve",
    "Frank",
    "Grace",
    "Heidi",
    "Ivan",
    "Judy",
  ],
  [
    "Karl",
    "Liam",
    "Mona",
    "Nina",
    "Oscar",
    "Paul",
    "Quinn",
    "Rita",
    "Sam",
    "Tina",
  ],
  ["Uma", "Vera", "Will", "Xena", "Yuri", "Zane", "Amy", "Ben", "Cleo", "Duke"],
  [
    "Elle",
    "Finn",
    "Gina",
    "Hank",
    "Ivy",
    "Jack",
    "Kara",
    "Leo",
    "Mick",
    "Nell",
  ],
  ["Omar", "Pia", "Quin", "Rex", "Sara", "Tom", "Una", "Vik", "Walt", "Xavi"],
  [
    "Yana",
    "Zack",
    "Abby",
    "Bill",
    "Cory",
    "Dina",
    "Earl",
    "Faye",
    "Gus",
    "Hope",
  ],
  [
    "Iris",
    "Joel",
    "Kurt",
    "Lara",
    "Moe",
    "Nate",
    "Opal",
    "Pete",
    "Quay",
    "Rosa",
  ],
  ["Sean", "Tess", "Ugo", "Vera", "Wes", "Xim", "Yves", "Zoe", "Ava", "Beau"],
  ["Chet", "Dora", "Evan", "Fay", "Glen", "Hope", "Ike", "Jill", "Kip", "Luz"],
  ["Max", "Nia", "Ollie", "Pam", "Quin", "Rae", "Sid", "Tia", "Uma", "Vic"],
];
