import type { Boxpool, User } from "./types";

export const testUser: User = {
  id: 1,
  name: "John Naeder",
  email: "madhead324@gmail.com",
};

export const boxpoolData: Boxpool = {
  id: 1,
  user: testUser,
  eventId: "401772827",
  boxNumbers: {
    homeBoxNumbers: [6, 2, 8, 0, 9, 1, 3, 4, 5, 7],
    awayBoxNumbers: [3, 5, 9, 0, 7, 1, 6, 2, 4, 8],
  },
  prizeNumbers: {
    gameScore: {
      FirstQuarter: "5000",
      SecondQuarter: "15000",
      ThirdQuarter: "5000",
      Final: "50000",
    },
    plusTwo: null,
    plusFive: null,
    reverse: null,
  },
  boxes: {
    1: { name: "Alice" },
    2: { name: "Bob" },
    3: { name: "Charlie" },
    4: { name: "Diana" },
    5: { name: "Ethan" },
    6: { name: "Fiona" },
    7: { name: "George" },
    8: { name: "Hannah" },
    9: { name: "Ivan" },
    10: { name: "Jasmine" },
    11: { name: "Kyle" },
    12: { name: "Laura" },
    13: { name: "Marcus" },
    14: { name: "Nina" },
    15: { name: "Oscar" },
    16: { name: "Paula" },
    17: { name: "Quentin" },
    18: { name: "Rachel" },
    19: { name: "Sam" },
    20: { name: "Tina" },
    21: { name: "Ursula" },
    22: { name: "Victor" },
    23: { name: "Wendy" },
    24: { name: "Xavier" },
    25: { name: "Yara" },
    26: { name: "Zane" },
    27: { name: "Amber" },
    28: { name: "Brian" },
    29: { name: "Cynthia" },
    30: { name: "Derek" },
    31: { name: "Elena" },
    32: { name: "Frank" },
    33: { name: "Grace" },
    34: { name: "Henry" },
    35: { name: "Isla" },
    36: { name: "Jack" },
    37: { name: "Kara" },
    38: { name: "Leo" },
    39: { name: "Maya" },
    40: { name: "Nathan" },
    41: { name: "Olivia" },
    42: { name: "Peter" },
    43: { name: "Queenie" },
    44: { name: "Ray" },
    45: { name: "Sophie" },
    46: { name: "Thomas" },
    47: { name: "Uma" },
    48: { name: "Vincent" },
    49: { name: "Willow" },
    50: { name: "Ximena" },
    51: { name: "Yvonne" },
    52: { name: "Zack" },
    53: { name: "Aaron" },
    54: { name: "Bella" },
    55: { name: "Carter" },
    56: { name: "Daisy" },
    57: { name: "Eli" },
    58: { name: "Faith" },
    59: { name: "Gavin" },
    60: { name: "Hazel" },
    61: { name: "Iris" },
    62: { name: "Jonas" },
    63: { name: "Kelsey" },
    64: { name: "Liam" },
    65: { name: "Mila" },
    66: { name: "Noah" },
    67: { name: "Opal" },
    68: { name: "Parker" },
    69: { name: "Quincy" },
    70: { name: "Riley" },
    71: { name: "Sierra" },
    72: { name: "Trent" },
    73: { name: "Ulysses" },
    74: { name: "Valerie" },
    75: { name: "Warren" },
    76: { name: "Xena" },
    77: { name: "Yusuf" },
    78: { name: "Zelda" },
    79: { name: "Allison" },
    80: { name: "Blake" },
    81: { name: "Clara" },
    82: { name: "Damon" },
    83: { name: "Elsa" },
    84: { name: "Felix" },
    85: { name: "Gianna" },
    86: { name: "Harvey" },
    87: { name: "Ingrid" },
    88: { name: "Jared" },
    89: { name: "Keira" },
    90: { name: "Logan" },
    91: { name: "Monica" },
    92: { name: "Neil" },
    93: { name: "Odette" },
    94: { name: "Preston" },
    95: { name: "Rosa" },
    96: { name: "Silas" },
    97: { name: "Tara" },
    98: { name: "Ulrich" },
    99: { name: "Vera" },
    100: { name: "Wyatt" },
  },
};
